### ISSUE TITLE
空指针异常

### ISSUE THREAD

**Issue by ZWinner** [hugeterry/UpdateDemo#13]
![image](https://cloud.githubusercontent.com/assets/12592337/18425583/3f2a140c-78ed-11e6-96cc-88df5111c37b.png)
![image](https://cloud.githubusercontent.com/assets/12592337/18425587/462898aa-78ed-11e6-80a5-c63c3bcbc5c9.png)

java.lang.RuntimeException: Unable to stop activity : java.lang.NullPointerException
    at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3381)
    at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3435)
    at android.app.ActivityThread.access$1100(ActivityThread.java:154)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1375)
    at android.os.Handler.dispatchMessage(Handler.java:110)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:5316)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:832)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:648)
    at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
    at cn.hugeterry.updatefun.UpdateFunGO.onStop(UpdateFunGO.java:101)
    at com.ztzx.xianhuobao.ui.activity.MainActivity.onStop(MainActivity.java:216)
    at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1218)
    at android.app.Activity.performStop(Activity.java:5502)
    at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3378)
    ... 11 more
java.lang.NullPointerException
    at cn.hugeterry.updatefun.UpdateFunGO.onStop(UpdateFunGO.java:101)
    at com.ztzx.xianhuobao.ui.activity.MainActivity.onStop(MainActivity.java:216)
    at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1218)
    at android.app.Activity.performStop(Activity.java:5502)
    at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3378)
    at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3435)
    at android.app.ActivityThread.access$1100(ActivityThread.java:154)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1375)
    at android.os.Handler.dispatchMessage(Handler.java:110)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:5316)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:832)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:648)
    at dalvik.system.NativeStart.main(Native Method)

**Comment by hugeterry** [comment]
请问你是在什么情况下出现这个异常？关闭了更新？
