### ISSUE TITLE
点击下载的时候闪退

### ISSUE THREAD

**Issue by EvlinLee** [hugeterry/UpdateDemo#9]
`java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
                                                                               at cn.hugeterry.updatefun.view.UpdateDialog$1.onClick(UpdateDialog.java:40)
                                                                               at android.view.View.performClick(View.java:4859)
                                                                               at android.view.View$PerformClick.run(View.java:20350)
                                                                               at android.os.Handler.handleCallback(Handler.java:815)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                               at android.os.Looper.loop(Looper.java:194)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5628)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at java.lang.reflect.Method.invoke(Method.java:372)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:956)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:751)`

**Comment by hugeterry** [comment]
你是在主界面的Activity的`onCreate()`下使用`UpdateFunGO.init(this);`的吗
还有，请确保在Activity中也添加了

```
 @Override
   protected void onResume() {
        super.onResume();
        UpdateFunGO.onResume(this);
    }
  @Override
     protected void onStop() {
         super.onStop();
         UpdateFunGO.onStop(this);
     }
```

再试试看

**Comment by EvlinLee** [comment]
@hugeterry 放在view设置id前就有问题，放在设置id后就没问题。还有一个问题就是关闭更新窗口后，只要没杀掉app，退出app再进来就不会显示更新窗口了

**Comment by hugeterry** [comment]
噢是的，需要放在`setContentView()`之后，稍后我在readme加上提示
是的，退出app有进程的话在内存中还占用着关闭窗口不用更新的数据，这是防止用户每次关闭窗口再打开应用仍出现提示更新的窗口，让用户厌倦。正常来说打开这次后关闭了窗口而app还在后台运行，重新打开是不会再提示的，等到用户下次再重新打开app时，才会再次提示更新😋
